import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  skill: [
    "skill/introduction",
    {
      label: "Web",
      type: "category",
      link: { type: "generated-index" },
      items: [
        {
          label: "Vue",
          type: "category",
          link: { type: "generated-index" },
          items: [{ type: "autogenerated", dirName: "skill/web/vue" }],
        },
        {
          label: "React",
          type: "category",
          link: { type: "generated-index" },
          items: [
            {
              type: "autogenerated",
              dirName: "skill/web/react",
            },
          ],
        },

        {
          label: "Css",
          type: "category",
          link: { type: "generated-index" },
          items: [
            {
              type: "autogenerated",
              dirName: "skill/web/css",
            },
          ],
        },
        {
          label: "Browser",
          type: "category",
          link: { type: "generated-index" },
          items: [
            {
              type: "autogenerated",
              dirName: "skill/web/browser",
            },
          ],
        },
      ],
    },
    {
      label: "源码阅读",
      type: "category",
      link: { type: "generated-index" },
      items: [
        {
          type: "autogenerated",
          dirName: "skill/source-code",
        },
      ],
    },
    {
      label: "JavaScript/Typescript",
      type: "category",
      link: { type: "generated-index" },
      items: [
        {
          type: "autogenerated",
          dirName: "skill/js&ts",
        },
      ],
    },
    {
      label: "vite",
      type: "category",
      link: { type: "generated-index" },
      items: [
        {
          type: "autogenerated",
          dirName: "skill/vite",
        },
      ],
    },
    {
      label: "日常作业",
      type: "category",
      link: { type: "generated-index" },
      items: [
        {
          type: "autogenerated",
          dirName: "skill/homework",
        },
      ],
    },
    {
      label: "JavaScript高级程序设计",
      type: "category",
      link: { type: "generated-index" },
      items: [
        {
          type: "autogenerated",
          dirName: "skill/js-advanced-programming",
        },
      ],
    },
    {
      label: "面试",
      type: "category",
      link: { type: "generated-index" },
      items: [
        {
          type: "autogenerated",
          dirName: "skill/interview",
        },
      ],
    },
    {
      label: "Git",
      type: "category",
      link: { type: "generated-index" },
      items: [
        {
          type: "autogenerated",
          dirName: "skill/git",
        },
      ],
    },
    {
      label: "操作系统",
      type: "category",
      link: { type: "generated-index" },
      items: [
        {
          type: "autogenerated",
          dirName: "skill/operating-system",
        },
      ],
    },
    {
      label: "算法",
      type: "category",
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "skill/algorithm",
        },
      ],
    },
    {
      label: "掘金热榜学习",
      type: "category",
      link: { type: "generated-index" },
      items: [
        {
          type: "autogenerated",
          dirName: "skill/juejin",
        },
      ],
    },
    {
      label: "月度总结与计划",
      type: "category",
      link: { type: "generated-index" },
      items: [
        {
          type: "autogenerated",
          dirName: "skill/monthly-summary",
        },
      ],
    },
  ],
  tools: ["tools/introduction", "tools/Math-Equations"],
};

module.exports = sidebars;
