import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  skill: [
    'skill/introduction',
    // {
    //   label: '代码规范',
    //   type: 'category',
    //   link: {
    //     type: 'doc',
    //     id: 'skill/code-specification/code-specification-guides',
    //   },
    //   items: [
    //     'skill/code-specification/eslint',
    //     'skill/code-specification/prettier',
    //     'skill/code-specification/stylelint',
    //     'skill/code-specification/editorconfig',
    //     'skill/code-specification/husky',
    //     'skill/code-specification/npmrc',
    //   ],
    // },
    {
      label: 'Web',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          label: 'Vue',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            'skill/web/vue/vue-reactive-data-object',
            'skill/web/vue/vue-reactive-data-array',
            'skill/web/vue/vue-reactive-data-basic-type',
            'skill/web/vue/pinia',
          ],
        },
        {
          label: 'React',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/web/react',
            },
          ],
        },
        {
          label: 'Css',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/web/css',
            },
          ],
        },
        {
          label: 'Browser',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/web/browser',
            },
          ],
        },
      ],
    },
    {
      label: 'JavaScript/Typescript',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/js&ts',
        },
      ],
    },
    {
      label: '日常作业',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/homework',
        },
      ],
    },
    {
      label:'JavaScript高级程序设计',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/js-advanced-programming',
        },
      ],
    },
    {
      label: 'Git',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/git',
        },
      ],
    },
    {
      label:'操作系统',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/operating-system',
        },
      ],
    },
    {
      label: '算法',
      type: 'category',
      link: {
        type: 'doc',
        id: 'skill/algorithm/algorithm-introduction',
      },
      items: [
        'skill/algorithm/basic',
        'skill/algorithm/two-sum',
        'skill/algorithm/three-sum',
        'skill/algorithm/sliding-window',
        'skill/algorithm/double-pointer',
        'skill/algorithm/interview',
      ],
    },
    
    {
      label: '月度总结与计划',
      type: 'category',
      link: { type: 'generated-index' },
      items:[
        {
          type: 'autogenerated',
          dirName: 'skill/monthly-summary',
        },
      ]

    }
    // {
    //   label: 'Docker',
    //   type: 'category',
    //   link: { type: 'generated-index' },
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'skill/docker',
    //     },
    //   ],
    // },
  ],
  tools: [
    'tools/introduction',
    'tools/Math-Equations',
],
}

module.exports = sidebars
